name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: opentofu/setup-opentofu@v2
    - name: Checking
      run: ls -a
    - name: Tofu initiation
      working-directory: ./simple_example
      run: |
        tofu init
        tofu plan -no-color
        echo ${{ steps.plan.outputs.stdout }}
        echo ${{ steps.plan.outputs.stderr }}
        echo ${{ steps.plan.outputs.exitcode }}
