name: CI

on: [push]

jobs:
  opentofu_run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    
    
    - uses: opentofu/setup-opentofu@v2
    - name: Checking
      run: ls -a
    - name: Tofu initiation
      working-directory: ./
      run: |
        export TWC_TOKEN=${{ secrets.MMM_TWC_TOKEN }}
        export OPENTOFU_WORKING_DIR=${{variables.OPENTOFU_WORKUNG_DIR}}
        export TF_VAR_image_id='ami-abc123'
        export TOFU_LOG=DEBUG
        export TF_LOG=TRACE
        infrastructure/scripts/run.sh
        