name: CI

on:
  push:
    branches:
      - test/trying_configurate_ci-cd_for_opentofu_with_simple_example

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: opentofu/setup-opentofu@v2
      with:
        ref: test/trying_configurate_ci-cd_for_opentofu_with_simple_example
    - name: Checking
      run: ls -a
    - name: Tofu initiation
      working-directory: ./simple_example
      run: |
        tofu init
        tofu plan -no-color
        echo ${{ steps.plan.outputs.stdout }}
        echo ${{ steps.plan.outputs.stderr }}
        echo ${{ steps.plan.outputs.exitcode }}
