name: CI

on: [push]

jobs:
  opentofu_run:
    outputs:
      main_ip: ${{ steps.tofu_init.outputs.main_ip }}
      worker_ip: ${{ steps.tofu_init.outputs.worker_ip }}
      argocd_node_server_root_pw: ${{ steps.tofu_init.outputs.argocd_node_server_root_pw }}
      main_server_root_pw: ${{ steps.tofu_init.outputs.main_server_root_pw }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - uses: opentofu/setup-opentofu@v2
    - name: Checking
      run: ls -a
    - name: Tofu initiation
      id: tofu_init
      env:
        TWC_TOKEN: ${{ secrets.TWC_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        OPENTOFU_WORKING_DIR: ${{vars.OPENTOFU_WORKUNG_DIR}}
      working-directory: ./
      run: |
        tofu version
        export TF_VAR_image_id='ami-abc123'
        export TOFU_LOG=DEBUG
        export TF_LOG=TRACE
        tofu -chdir="$OPENTOFU_WORKING_DIR" init -upgrade
        tofu -chdir="$OPENTOFU_WORKING_DIR" plan -no-color
        tofu -chdir="$OPENTOFU_WORKING_DIR" apply -auto-approve -lock-timeout=360s
        tofu -chdir="$OPENTOFU_WORKING_DIR" output
        tofu -chdir="$OPENTOFU_WORKING_DIR" state list | grep main-server
        export MAIN_IP=$(tofu -chdir="${{ vars.OPENTOFU_WORKUNG_DIR }}" output -json main_server_ip | jq -r '.')
        echo $(tofu -chdir="${{ vars.OPENTOFU_WORKUNG_DIR }}" output -json main_server_ip | jq -r '.')
        export WORKER_IP=$(tofu -chdir="${{ vars.OPENTOFU_WORKUNG_DIR }}" output -json argocd_node_ip | jq -r '.')
        echo $(tofu -chdir="${{ vars.OPENTOFU_WORKUNG_DIR }}" output -json argocd_node_ip | jq -r '.')
        export MAIN_PW=$(tofu -chdir="${{ vars.OPENTOFU_WORKUNG_DIR }}" output -json main_server_root_pw | jq -r '.')
        echo $(tofu -chdir="${{ vars.OPENTOFU_WORKUNG_DIR }}" output -json main_server_root_pw | jq -r '.')
        export WORKER_PW=$(tofu -chdir="${{ vars.OPENTOFU_WORKUNG_DIR }}" output -json argocd_node_server_root_pw | jq -r '.')
        echo $(tofu -chdir="${{ vars.OPENTOFU_WORKUNG_DIR }}" output -json argocd_node_server_root_pw | jq -r '.')
        echo "main_ip=$MAIN_IP" >> $GITHUB_OUTPUT
        echo "worker_ip=$WORKER_IP" >> $GITHUB_OUTPUT
        echo "main_server_root_pw=$MAIN_PW" >> $GITHUB_OUTPUT
        echo "argocd_node_server_root_pw=$WORKER_PW" >> $GITHUB_OUTPUT

  ansible_setup:
    runs-on: ubuntu-latest
    needs: opentofu_run
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible and dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass
          ansible-galaxy collection install kubernetes.core
      - name: Add server keys to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "needs.opentofu_run.outputs.main_ip"
          echo ${{ needs.opentofu_run.outputs.main_ip }}
          ssh-keyscan ${{ needs.opentofu_run.outputs.main_ip }} >> ~/.ssh/known_hosts
          ssh-keyscan ${{ needs.opentofu_run.outputs.worker_ip }} >> ~/.ssh/known_hosts

      - name: Create Ansible inventory
        run: |
          cat > inventory.ini << EOF
          [k3s_servers]
          ${{ needs.opentofu_run.outputs.main_ip }} ansible_user=root ansible_password='${{ needs.opentofu_run.outputs.main_server_root_pw }}'

          [k3s_agents]
          ${{ needs.opentofu_run.outputs.worker_ip }} ansible_user=root ansible_password='${{ needs.opentofu_run.outputs.argocd_node_server_root_pw }}'

          [k3s_cluster:children]
          k3s_servers
          k3s_agents

          [all:vars]
          ansible_ssh_common_args='-o StrictHostKeyChecking=no'
          ansible_become=yes
          ansible_become_method=sudo
          EOF
      - name: Run install_k3s_on_servers.yml
        run: ansible-playbook -i inventory.ini ansible/playbooks/install_k3s_on_servers.yml
      - name: Run join_servers_to_k3s_cluster.yml
        run: ansible-playbook -i inventory.ini ansible/playbooks/join_servers_to_k3s_cluster.yml
      - name: Run install_k3s_on_servers.yml
        run: ansible-playbook -i inventory.ini ansible/playbooks/install_k3s_on_servers.yml
      
